### ISSUE TITLE
Header parsing problems when whitespace in Fasta header

### ISSUE THREAD

**Issue by rauerc** [UCL/cathpy#12]
cath-align-scorecons crashes when there is a space in the header line. The fasta file 

```
>seq1 bla
TTTTLLASAMLSASVFALTDPPVDPVDPVDPTDPPSSD
>seq2 bla
TTTTLLASAMLSASVFALTDPPVDPVDPVDPTDPPSSD
```

produces the following output (when I remove the space in the headers it works normally)

```
Traceback (most recent call last):
  File "/home/clemens/miniconda3/lib/python3.7/site-packages/cathpy/core/align.py", line 32, in __init__
    hdr_info = Sequence.split_hdr(hdr)
  File "/home/clemens/miniconda3/lib/python3.7/site-packages/cathpy/core/align.py", line 283, in split_hdr
    for f in meta_parts.split('=', maxsplit=1):
AttributeError: 'list' object has no attribute 'split'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/clemens/miniconda3/bin/cath-align-scorecons", line 45, in <module>
    aln = Align.from_fasta(args.in_file)
  File "/home/clemens/miniconda3/lib/python3.7/site-packages/cathpy/core/align.py", line 889, in from_fasta
    aln.read_sequences_from_fasta(fasta_io)
  File "/home/clemens/miniconda3/lib/python3.7/site-packages/cathpy/core/align.py", line 1062, in read_sequences_from_fasta
    seq = Sequence(current_hdr, current_seq)
  File "/home/clemens/miniconda3/lib/python3.7/site-packages/cathpy/core/align.py", line 34, in __init__
    raise err.GeneralError('caught error while parsing sequence header: '+hdr)

```

**Comment by sillitoe** [comment]
Fixed in #17 - released as v0.4.0 - thanks for reporting!
