### ISSUE TITLE
Header parsing fails when multiple '-' in header (e.g. negative starting boundary)

### ISSUE THREAD

**Issue by bordin89** [UCL/cathpy#9]
cath-align-scorecons fails when there are multiple '-' characters in the header. This was first detected when a CATH domain had a negative residue boundary.

```
Traceback (most recent call last):
  File "/cath/people2/ucbtnb4/funfams-4.3/venv/lib64/python3.6/site-packages/cathpy/core/align.py", line 32, in __init__
    hdr_info = Sequence.split_hdr(hdr)
  File "/cath/people2/ucbtnb4/funfams-4.3/venv/lib64/python3.6/site-packages/cathpy/core/align.py", line 276, in split_hdr
    (start, stop) = seg_str.split('-')
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):

  File "/cath/people2/ucbtnb4/funfams-4.3/venv/bin/cath-align-scorecons", line 45, in <module>
    aln = Align.from_fasta(args.in_file)
  File "/cath/people2/ucbtnb4/funfams-4.3/venv/lib64/python3.6/site-packages/cathpy/core/align.py", line 889, in from_fasta
    aln.read_sequences_from_fasta(fasta_io)
  File "/cath/people2/ucbtnb4/funfams-4.3/venv/lib64/python3.6/site-packages/cathpy/core/align.py", line 1062, in read_sequences_from_fasta
    seq = Sequence(current_hdr, current_seq)
  File "/cath/people2/ucbtnb4/funfams-4.3/venv/lib64/python3.6/site-packages/cathpy/core/align.py", line 34, in __init__

    raise err.GeneralError('caught error while parsing sequence header: '+hdr)
cathpy.core.error.GeneralError: caught error while parsing sequence header: cath|4_3_0|4w5hA00/-1-211
```

**Comment by sillitoe** [comment]
I think #17 addresses this issue. 

Essentially segment start/stops are now assumed to be strings unless explicitly told to parse them as numbers. If they *are* treated as numbers then they should always start at 1. 

The only reason to ever see negative "numbers" is when these are actually strings (from ATOM labels). If so, these can only be interpreted when using a sequence to structure mapping (GCF).
